load("//bazel/java:package.bzl", "java_library")

java_library(
    name = "project",
    srcs = [
        "ExclusiveBlobProjection.java",
        "IdLookupFactory.java",
        "InclusiveBlobProject.java",
        "PathTrie.java",
        "ProjectFactory.java",
        "ProjectSpec.java",
        "ProjectStage.java",
        "ProjectStrategy.java",
        "ProjectionSource.java",
        "ProjectionTransform.java",
        "StoredSourceStrategy.java",
        "UnorderedProjectFactory.java",
    ],
    visibility = ["//visibility:public"],
    exports = ["@maven//:org_mongodb_bson"],
    deps = [
        "//src/main/java/com/xgen/mongot/index/definition",
        "//src/main/java/com/xgen/mongot/index/lucene/field",
        "//src/main/java/com/xgen/mongot/index/lucene/query/util",
        "//src/main/java/com/xgen/mongot/util",
        "//src/main/java/com/xgen/mongot/util/bson",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_errorprone_error_prone_annotations",
        "@maven//:com_google_guava_guava",
        "@maven//:org_apache_lucene_lucene_core",
        "@maven//:org_jetbrains_annotations",
        "@maven//:org_mongodb_bson",
    ],
)
