load("//bazel/buildifier:repos.bzl", "buildifier_repos")
load("//bazel/common:repos.bzl", "common_repos")
load("//bazel/docker:repos.bzl", "docker_repos")
load("//bazel/go:repos.bzl", "go_repos")
load("//bazel/java:repos.bzl", "java_repos")
load("//bazel/javascript:repos.bzl", "javascript_repos")
load("//bazel/proto:repos.bzl", "proto_repos")
load("//bazel/python:repos.bzl", "python_repos")
load("//bazel/rust:repos.bzl", "rust_repos")
load("//bazel/shell:repos.bzl", "shell_repos")
load("//bazel/tools:repos.bzl", "tools_repos")

def mongot_repos():
    common_repos()
    buildifier_repos()
    docker_repos()
    go_repos()
    java_repos()
    javascript_repos()
    proto_repos()
    python_repos()
    rust_repos()
    shell_repos()
    tools_repos()
