"""Module extension that creates the cross-compilation sysroot archives.

Sysroots are generated by scripts/sysroots/generate_sysroot.sh and uploaded to S3.
Used by the hermetic LLVM toolchain for cross-compilation to linux x86_64/aarch64.
"""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def _impl(_mctx):
    http_archive(
        name = "sysroot_ubuntu1804_aarch64",
        integrity = "sha256-jZ3oqi6sNliEHieYBkzgaz+8LxsWEIvVzHjV7WgZEbo=",
        strip_prefix = "ubuntu1804-aarch64",
        urls = ["https://search-build-and-release-3p-tools.s3.us-east-2.amazonaws.com/sysroots/ubuntu1804-aarch64.tar.gz"],
    )
    http_archive(
        name = "sysroot_ubuntu1804_x86_64",
        integrity = "sha256-qxg9fi4JmkTnonyYmfm5HYU0fd03ZM9BGF0Xe8bIUpA=",
        strip_prefix = "ubuntu1804-x86_64",
        urls = ["https://search-build-and-release-3p-tools.s3.us-east-2.amazonaws.com/sysroots/ubuntu1804-x86_64.tar.gz"],
    )
    http_archive(
        name = "sysroot_amazonlinux2_aarch64",
        integrity = "sha256-yuTUkRdmeSBUTCZ8rH+0ma2uDVJimlf9Bcwvj0s35+c=",
        strip_prefix = "amazonlinux2-aarch64",
        urls = ["https://search-build-and-release-3p-tools.s3.us-east-2.amazonaws.com/sysroots/amazonlinux2-aarch64.tar.gz"],
    )
    http_archive(
        name = "sysroot_amazonlinux2_x86_64",
        integrity = "sha256-VaSnDDhpZzc3liZGhXUogkXzSrB2x91YJv2Nq3A6V2Y=",
        strip_prefix = "amazonlinux2-x86_64",
        urls = ["https://search-build-and-release-3p-tools.s3.us-east-2.amazonaws.com/sysroots/amazonlinux2-x86_64.tar.gz"],
    )

cc_repos = module_extension(implementation = _impl)
