load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# https://github.com/bazel-contrib/toolchains_llvm/releases
_TOOLCHAINS_LLVM_VERSION = "1.1.2"

def cc_repos():
    http_archive(
        name = "toolchains_llvm",
        integrity = "sha256-xIKgzXHVC3buqCDMSRLXtyqw7X6Lox77xwnlOyBzcPg=",
        strip_prefix = "toolchains_llvm-{}".format(_TOOLCHAINS_LLVM_VERSION),
        urls = [
            "https://github.com/bazel-contrib/toolchains_llvm/archive/refs/tags/v{}.tar.gz".format(_TOOLCHAINS_LLVM_VERSION),
        ],
    )

    # Cross-compilation sysroots. Generated by scripts/sysroots/generate_sysroot.sh.
    # These are used for hermetic llvm builds of native code on linux.
    # Sysroots should use the oldest platform we target for glibc compatibility.
    #
    # To generate:
    #   ./scripts/sysroots/generate_sysroot.sh --arch x86_64|aarch64 --output-tar <path>
    http_archive(
        name = "sysroot_ubuntu1804_aarch64",
        integrity = "sha256-jZ3oqi6sNliEHieYBkzgaz+8LxsWEIvVzHjV7WgZEbo=",
        strip_prefix = "ubuntu1804-aarch64",
        urls = [
            "https://search-build-and-release-3p-tools.s3.us-east-2.amazonaws.com/sysroots/ubuntu1804-aarch64.tar.gz",
        ],
    )

    http_archive(
        name = "sysroot_ubuntu1804_x86_64",
        integrity = "sha256-qxg9fi4JmkTnonyYmfm5HYU0fd03ZM9BGF0Xe8bIUpA=",
        strip_prefix = "ubuntu1804-x86_64",
        urls = [
            "https://search-build-and-release-3p-tools.s3.us-east-2.amazonaws.com/sysroots/ubuntu1804-x86_64.tar.gz",
        ],
    )

    http_archive(
        name = "sysroot_amazonlinux2_aarch64",
        integrity = "sha256-yuTUkRdmeSBUTCZ8rH+0ma2uDVJimlf9Bcwvj0s35+c=",
        strip_prefix = "amazonlinux2-aarch64",
        urls = [
            "https://search-build-and-release-3p-tools.s3.us-east-2.amazonaws.com/sysroots/amazonlinux2-aarch64.tar.gz",
        ],
    )

    http_archive(
        name = "sysroot_amazonlinux2_x86_64",
        integrity = "sha256-VaSnDDhpZzc3liZGhXUogkXzSrB2x91YJv2Nq3A6V2Y=",
        strip_prefix = "amazonlinux2-x86_64",
        urls = [
            "https://search-build-and-release-3p-tools.s3.us-east-2.amazonaws.com/sysroots/amazonlinux2-x86_64.tar.gz",
        ],
    )
