load("//bazel/java:package.bzl", "java_library")

java_library(
    name = "updater",
    srcs = [
        "ConfigUpdater.java",
        "RetriableConfigUpdateException.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/xgen/mongot/util",
    ],
)
