#!/bin/sh
set -e

install -d -m 0750 -o root -g mongod /etc/mongot/secrets

chown -R mongod:mongod /var/lib/mongot
chown -R mongod:mongod /var/log/mongot
chown -R root:mongod   /etc/mongot
chmod 0750             /etc/mongot
chmod 0640             /etc/mongot/mongot.yml || true

#DEBHELPER#

exit 0
