package com.xgen.mongot.logging;

import com.google.errorprone.annotations.DoNotMock;
import java.util.HashMap;
import java.util.Map;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.spi.LoggingEventBuilder;

/**
 * This class is a wrapper around SLF4J's {@link Logger} that allows you to add key-value pairs that
 * will be appended to every log message.
 */
@DoNotMock
public class DefaultKeyValueLogger {
  private final Logger logger;
  private final Map<String, Object> defaultKeyValuePairs;

  DefaultKeyValueLogger(Logger logger, HashMap<String, Object> defaultKeyValuePairs) {
    this.logger = logger;
    this.defaultKeyValuePairs = new HashMap<>(defaultKeyValuePairs);
  }

  /**
   * Creates a new instance of {@code DefaultKeyValueLogger} for the specified class type
   * with the given default key-value pairs.
   *
   * <p>This method obtains a logger instance for the provided class. All logs generated by this
   * logger will have the specified key-value pairs appended to their logging context. The method
   * creates a copy of the specified key-value pairs, so modifications to the original map after
   * this method call will not affect the log entries.
   *
   * @param clazz the class for which the logger instance should be created
   * @param defaultKeyValuePairs A map of key-value pairs to be copied and used for all log entries;
   *                             changing the map after this method call will not affect the logger.
   *                             A {@code HashMap} is required so that null values are permitted.
   *
   * @return a {@code DefaultKeyValueLogger} instance configured with the appropriate logger
   *         and the specified default key-value pairs
   */
  public static DefaultKeyValueLogger getLogger(
      Class<?> clazz, HashMap<String, Object> defaultKeyValuePairs) {
    return new DefaultKeyValueLogger(LoggerFactory.getLogger(clazz), defaultKeyValuePairs);
  }

  public LoggingEventBuilder atTrace() {
    return createBuilder(this.logger.atTrace());
  }

  public LoggingEventBuilder atDebug() {
    return createBuilder(this.logger.atDebug());
  }

  public LoggingEventBuilder atInfo() {
    return createBuilder(this.logger.atInfo());
  }

  public LoggingEventBuilder atWarn() {
    return createBuilder(this.logger.atWarn());
  }

  public LoggingEventBuilder atError() {
    return createBuilder(this.logger.atError());
  }

  private LoggingEventBuilder createBuilder(LoggingEventBuilder builder) {
    this.defaultKeyValuePairs.forEach(builder::addKeyValue);
    return builder;
  }

  public void trace(String message) {
    this.atTrace().log(message);
  }

  public void trace(String message, @Nullable Object... args) {
    this.atTrace().log(message, args);
  }

  public void trace(String message, @Nullable Throwable cause) {
    this.atTrace().setCause(cause).log(message);
  }

  public void debug(String message) {
    this.atDebug().log(message);
  }

  public void debug(String message, @Nullable Object... args) {
    this.atDebug().log(message, args);
  }

  public void debug(String message, Throwable cause) {
    this.atDebug().setCause(cause).log(message);
  }

  public void info(String message) {
    this.atInfo().log(message);
  }

  public void info(String message, @Nullable Object... args) {
    this.atInfo().log(message, args);
  }

  public void info(String message, @Nullable Throwable cause) {
    this.atInfo().setCause(cause).log(message);
  }

  public void warn(String message) {
    this.atWarn().log(message);
  }

  public void warn(String message, @Nullable Object... args) {
    this.atWarn().log(message, args);
  }

  public void warn(String message, @Nullable Throwable cause) {
    this.atWarn().setCause(cause).log(message);
  }

  public void error(String message) {
    this.atError().log(message);
  }

  public void error(String message, @Nullable Object... args) {
    this.atError().log(message, args);
  }

  public void error(String message, @Nullable Throwable cause) {
    this.atError().setCause(cause).log(message);
  }
}
